name: Update Equity Data

on:
  schedule:
    # Runs at 6 PM UTC (11:30 PM IST) on weekdays (Monday to Friday)
    - cron: '0 18 * * 1-5'
  push:
    branches:
      - main

jobs:
  update:
    name: Update today's equity data
    runs-on: ubuntu-latest

    steps:
    # Get current date in YYYYMMDD format
    - name: Get current date
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: "YYYYMMDD"
        timezone: 'Asia/Kolkata'

    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    # Set up Python environment
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'

    # Install dependencies
    - name: Install dependencies from requirements.txt
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    # Run data update script
    - name: Run data update script
      run: |
        python3 get_todays_date.py

    # Configure Git and push changes to main
    - name: Push changes to main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        # Add and commit changes
        git add -A
        git commit -m "Updated data for ${{ steps.current-time.outputs.formattedTime }}"

        # Push changes directly to the main branch
        git push origin main
