name: Update Equity Data

on:
  schedule:
    # This runs at 6 PM UTC (11:30 PM IST) on weekdays (Monday to Friday)
    - cron: '0 18 * * 1-5'
  push:
    branches:
      - main

jobs:
  update:
    name: Update today's equity data
    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: "YYYYMMDD"
        timezone: 'Asia/Kolkata'

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'

    - name: Install dependencies from requirements.txt
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download and extract data file
      run: |
        # Define the file URL and path
        FILE_URL="https://archives.nseindia.com/content/cm/BhavCopy_NSE_CM_0_0_0_${{ steps.current-time.outputs.formattedTime }}_F_0000.csv.zip"
        FILE_PATH="data/BhavCopy_${{ steps.current-time.outputs.formattedTime }}.zip"
        
        echo "Attempting to download file: $FILE_URL"

        # Attempt to download the file
        curl --fail --silent --show-error --output $FILE_PATH $FILE_URL
        if [ $? -ne 0 ]; then
          echo "Error: Failed to download the file for ${{ steps.current-time.outputs.formattedTime }}. Stopping the workflow."
          exit 1  # Exit with failure
        fi

        # Attempt to extract the file
        unzip -o $FILE_PATH -d data/
        if [ $? -ne 0 ]; then
          echo "Error: Failed to extract the file for ${{ steps.current-time.outputs.formattedTime }}. Stopping the workflow."
          exit 1  # Exit with failure
        fi


    - name: Run data update script
      run: |
        python3 get_todays_date.py

    - name: Commit changes
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add -A
        git commit -m "Updated data for ${steps.current-time.outputs.formattedTime}"
        git push origin main

    - name: Verify commit and push
      run: git log -1
